import { Agent, Team } from './types';
import { AGENT_PROMPTS } from './prompts/agentPrompts';

export const AGENTS: Agent[] = [
  {
    id: 'president',
    name: 'プレジデント',
    alias: 'president',
    role: '最高意思決定者',
    team: Team.LEADERSHIP,
    systemPrompt: AGENT_PROMPTS['president'],
  },
  {
    id: 'orchestrator',
    name: 'プロジェクト・オーケストレーター',
    alias: 'orchestrator',
    role: '統括管理者',
    team: Team.LEADERSHIP,
    systemPrompt: AGENT_PROMPTS['orchestrator'],
  },
  // --- Strategic Insight Team ---
  { id: 'A1', name: 'マーケット・アナリスト', alias: 'analyst', role: '市場分析官', team: Team.STRATEGIC_INSIGHT, systemPrompt: AGENT_PROMPTS['A1'] },
  { id: 'A2', name: 'ユーザー・エスノグラファー', alias: 'ethno', role: 'ユーザー洞察専門家', team: Team.STRATEGIC_INSIGHT, systemPrompt: AGENT_PROMPTS['A2'] },
  { id: 'A11', name: 'トレンド・フォーキャスター', alias: 'forecast', role: '未来予測アナリスト', team: Team.STRATEGIC_INSIGHT, systemPrompt: AGENT_PROMPTS['A11'] },
  { id: 'A26', name: '行動心理学者', alias: 'psychologist', role: '行動心理分析官', team: Team.STRATEGIC_INSIGHT, systemPrompt: AGENT_PROMPTS['A26'] },
  { id: 'B4', name: '経営企画ストラテジスト', alias: 'corp_strategy', role: '全社戦略立案担当', team: Team.STRATEGIC_INSIGHT, systemPrompt: AGENT_PROMPTS['B4'] },
  { id: 'B13', name: '財務アナリスト', alias: 'financial_analyst', role: '財務分析担当', team: Team.STRATEGIC_INSIGHT, systemPrompt: AGENT_PROMPTS['B13'] },
  // --- Product & Design Team ---
  { id: 'A3', name: 'アイデア・ジェネレーター', alias: 'idea', role: 'アイデア発想家', team: Team.PRODUCT_DESIGN, systemPrompt: AGENT_PROMPTS['A3'] },
  { id: 'A4', name: 'UXアーキテクト', alias: 'ux', role: '体験設計士', team: Team.PRODUCT_DESIGN, systemPrompt: AGENT_PROMPTS['A4'] },
  { id: 'A8', name: 'UI/UXデザイナー', alias: 'design', role: 'UI/UX設計者', team: Team.PRODUCT_DESIGN, systemPrompt: AGENT_PROMPTS['A8'] },
  { id: 'A9', name: 'コピーライター', alias: 'copy', role: '言葉の専門家', team: Team.PRODUCT_DESIGN, systemPrompt: AGENT_PROMPTS['A9'] },
  { id: 'A21', name: 'プロダクト・マネージャー', alias: 'pm', role: '製品ロードマップ管理者', team: Team.PRODUCT_DESIGN, systemPrompt: AGENT_PROMPTS['A21'] },
  { id: 'A28', name: 'サウンド・デザイナー', alias: 'sound', role: '聴覚体験設計者', team: Team.PRODUCT_DESIGN, systemPrompt: AGENT_PROMPTS['A28'] },
  // --- Technology Development Team ---
  { id: 'A5', name: 'テック・フィジビリティ・チェッカー', alias: 'tech', role: '技術実現性評価者', team: Team.TECH_DEVELOPMENT, systemPrompt: AGENT_PROMPTS['A5'] },
  { id: 'A15', name: 'QA & エシックス・エンジニア', alias: 'qa', role: '品質・倫理監査官', team: Team.TECH_DEVELOPMENT, systemPrompt: AGENT_PROMPTS['A15'] },
  { id: 'A23', name: 'DevOpsスペシャリスト', alias: 'devops', role: '開発・運用自動化担当', team: Team.TECH_DEVELOPMENT, systemPrompt: AGENT_PROMPTS['A23'] },
  { id: 'A25', name: 'インターナショナリゼーション・スペシャリスト', alias: 'i18n', role: '国際化対応専門家', team: Team.TECH_DEVELOPMENT, systemPrompt: AGENT_PROMPTS['A25'] },
  { id: 'A27', name: 'クリエイティブ・テクノロジスト', alias: 'creative_tech', role: '先端技術体験開発者', team: Team.TECH_DEVELOPMENT, systemPrompt: AGENT_PROMPTS['A27'] },
  { id: 'B27', name: 'テクニカル・サポート・スペシャリスト', alias: 'tech_support', role: '技術問い合わせ対応担当', team: Team.TECH_DEVELOPMENT, systemPrompt: AGENT_PROMPTS['B27'] },
  // --- Infrastructure & Security Team ---
  { id: 'A13', name: 'セキュリティ・アーキテクト', alias: 'security', role: '情報セキュリティ専門家', team: Team.INFRA_SECURITY, systemPrompt: AGENT_PROMPTS['A13'] },
  { id: 'A22', name: 'SRE (サイト信頼性エンジニア)', alias: 'sre', role: 'サービス安定稼働責任者', team: Team.INFRA_SECURITY, systemPrompt: AGENT_PROMPTS['A22'] },
  { id: 'B5', name: '内部監査スペシャリスト', alias: 'audit', role: '内部統制評価担当', team: Team.INFRA_SECURITY, systemPrompt: AGENT_PROMPTS['B5'] },
  { id: 'B18', name: 'データプライバシー・オフィサー', alias: 'dpo', role: '個人情報保護監督者', team: Team.INFRA_SECURITY, systemPrompt: AGENT_PROMPTS['B18'] },
  { id: 'B25', name: 'ITサービスデスク・マネージャー', alias: 'it_servicedesk', role: '社内ITサポート担当', team: Team.INFRA_SECURITY, systemPrompt: AGENT_PROMPTS['B25'] },
  { id: 'B26', name: 'クラウド・インフラ・エンジニア', alias: 'cloud_infra', role: 'クラウドインフラ構築・運用担当', team: Team.INFRA_SECURITY, systemPrompt: AGENT_PROMPTS['B26'] },
  // --- Marketing & Brand Team ---
  { id: 'A10', name: 'データ・ビジュアライザー', alias: 'viz', role: 'データ可視化担当', team: Team.MARKETING_BRAND, systemPrompt: AGENT_PROMPTS['A10'] },
  { id: 'A14', name: 'Go-to-Market スペシャリスト', alias: 'gtm', role: '市場投入戦略家', team: Team.MARKETING_BRAND, systemPrompt: AGENT_PROMPTS['A14'] },
  { id: 'A16', name: 'コンテンツ・ストラテジスト', alias: 'content', role: 'コンテンツ戦略家', team: Team.MARKETING_BRAND, systemPrompt: AGENT_PROMPTS['A16'] },
  { id: 'A18', name: 'ソーシャルメディア・マネージャー', alias: 'social', role: 'SNS運用担当', team: Team.MARKETING_BRAND, systemPrompt: AGENT_PROMPTS['A18'] },
  { id: 'A19', name: 'ブランド・ガーディアン', alias: 'brand', role: 'ブランド管理責任者', team: Team.MARKETING_BRAND, systemPrompt: AGENT_PROMPTS['A19'] },
  { id: 'B30', name: 'イベント・プランナー', alias: 'event_planner', role: 'イベント企画・実行担当', team: Team.MARKETING_BRAND, systemPrompt: AGENT_PROMPTS['B30'] },
  // --- Sales & Partnerships Team ---
  { id: 'A20', name: 'パートナーシップ・デベロッパー', alias: 'partnership', role: '事業開発・提携担当', team: Team.SALES_PARTNERSHIPS, systemPrompt: AGENT_PROMPTS['A20'] },
  { id: 'B7', name: 'インサイドセールス・スペシャリスト', alias: 'inside_sales', role: '内勤営業・商談創出担当', team: Team.SALES_PARTNERSHIPS, systemPrompt: AGENT_PROMPTS['B7'] },
  { id: 'B8', name: 'フィールドセールス・エグゼクティブ', alias: 'field_sales', role: '外勤営業・クロージング担当', team: Team.SALES_PARTNERSHIPS, systemPrompt: AGENT_PROMPTS['B8'] },
  { id: 'B9', name: 'アカウントマネージャー', alias: 'account_manager', role: '既存顧客担当営業', team: Team.SALES_PARTNERSHIPS, systemPrompt: AGENT_PROMPTS['B9'] },
  { id: 'B10', name: 'セールス・イネーブルメント・プランナー', alias: 'sales_enablement', role: '営業企画・育成担当', team: Team.SALES_PARTNERSHIPS, systemPrompt: AGENT_PROMPTS['B10'] },
  { id: 'B11', name: 'チャネル・パートナー・マネージャー', alias: 'channel_manager', role: '代理店担当', team: Team.SALES_PARTNERSHIPS, systemPrompt: AGENT_PROMPTS['B11'] },
  // --- Communications & Customer Relations Team ---
  { id: 'A17', name: 'PR & メディア・リレーションズ', alias: 'pr', role: '広報・メディア担当', team: Team.COMMUNICATIONS_CUSTOMER_RELATIONS, systemPrompt: AGENT_PROMPTS['A17'] },
  { id: 'A24', name: 'カスタマー・サクセス・アナリスト', alias: 'cs', role: '顧客成功分析官', team: Team.COMMUNICATIONS_CUSTOMER_RELATIONS, systemPrompt: AGENT_PROMPTS['A24'] },
  { id: 'B6', name: 'IR（投資家向け広報）スペシャリスト', alias: 'ir', role: '投資家向け広報担当', team: Team.COMMUNICATIONS_CUSTOMER_RELATIONS, systemPrompt: AGENT_PROMPTS['B6'] },
  { id: 'B22', name: '組織文化デザイナー', alias: 'org_culture', role: '組織文化醸成担当', team: Team.COMMUNICATIONS_CUSTOMER_RELATIONS, systemPrompt: AGENT_PROMPTS['B22'] },
  { id: 'B23', name: '社内広報スペシャリスト', alias: 'internal_comms', role: '社内広報担当', team: Team.COMMUNICATIONS_CUSTOMER_RELATIONS, systemPrompt: AGENT_PROMPTS['B23'] },
  { id: 'B24', name: '危機管理広報マネージャー', alias: 'crisis_comms', role: '危機管理広報担当', team: Team.COMMUNICATIONS_CUSTOMER_RELATIONS, systemPrompt: AGENT_PROMPTS['B24'] },
  // --- Finance & Business Strategy Team ---
  { id: 'A7', name: 'ビジネス・ストラテジスト', alias: 'biz', role: '事業戦略家', team: Team.FINANCE_BUSINESS_STRATEGY, systemPrompt: AGENT_PROMPTS['A7'] },
  { id: 'B1', name: 'CFO（最高財務責任者）AI', alias: 'cfo_ai', role: '最高財務責任者', team: Team.FINANCE_BUSINESS_STRATEGY, systemPrompt: AGENT_PROMPTS['B1'] },
  { id: 'B12', name: '経理担当アカウンタント', alias: 'accountant', role: '経理担当', team: Team.FINANCE_BUSINESS_STRATEGY, systemPrompt: AGENT_PROMPTS['B12'] },
  { id: 'B14', name: '予算管理プランナー', alias: 'budget_planner', role: '予実管理担当', team: Team.FINANCE_BUSINESS_STRATEGY, systemPrompt: AGENT_PROMPTS['B14'] },
  { id: 'B15', name: '調達・購買スペシャリスト', alias: 'procurement', role: '調達・購買担当', team: Team.FINANCE_BUSINESS_STRATEGY, systemPrompt: AGENT_PROMPTS['B15'] },
  { id: 'B29', name: 'サプライチェーン・マネージャー', alias: 'supply_chain', role: '供給網管理担当', team: Team.FINANCE_BUSINESS_STRATEGY, systemPrompt: AGENT_PROMPTS['B29'] },
  // --- People & Operations Team ---
  { id: 'A30', name: 'サステナビリティ・ストラテジスト', alias: 'sustainability', role: '持続可能性戦略家', team: Team.PEOPLE_OPERATIONS, systemPrompt: AGENT_PROMPTS['A30'] },
  { id: 'B2', name: 'CHRO（最高人事責任者）AI', alias: 'chro_ai', role: '最高人事責任者', team: Team.PEOPLE_OPERATIONS, systemPrompt: AGENT_PROMPTS['B2'] },
  { id: 'B19', name: 'タレント・アクイジション・スペシャリスト', alias: 'talent_acquisition', role: '採用担当', team: Team.PEOPLE_OPERATIONS, systemPrompt: AGENT_PROMPTS['B19'] },
  { id: 'B20', name: 'ラーニング＆デベロップメント・プランナー', alias: 'ld_planner', role: '研修・育成担当', team: Team.PEOPLE_OPERATIONS, systemPrompt: AGENT_PROMPTS['B20'] },
  { id: 'B21', name: 'パフォーマンス・アナリスト', alias: 'performance_analyst', role: '人事評価担当', team: Team.PEOPLE_OPERATIONS, systemPrompt: AGENT_PROMPTS['B21'] },
  { id: 'B28', name: 'オフィス・マネージャー', alias: 'office_manager', role: 'ファシリティ管理担当', team: Team.PEOPLE_OPERATIONS, systemPrompt: AGENT_PROMPTS['B28'] },
  // --- Legal & Compliance Team ---
  { id: 'A6', name: 'リスク・アセッサー', alias: 'risk', role: 'リスク評価官', team: Team.LEGAL_COMPLIANCE, systemPrompt: AGENT_PROMPTS['A6'] },
  { id: 'A12', name: 'リーガル・アドバイザー', alias: 'legal', role: '法務・コンプライアンス担当', team: Team.LEGAL_COMPLIANCE, systemPrompt: AGENT_PROMPTS['A12'] },
  { id: 'A29', name: 'AI倫理スペシャリスト', alias: 'ai_ethics', role: 'AI倫理監査官', team: Team.LEGAL_COMPLIANCE, systemPrompt: AGENT_PROMPTS['A29'] },
  { id: 'B3', name: 'CCO（最高コンプライアンス責任者）AI', alias: 'cco_ai', role: '最高コンプライアンス責任者', team: Team.LEGAL_COMPLIANCE, systemPrompt: AGENT_PROMPTS['B3'] },
  { id: 'B16', name: '契約管理スペシャリスト', alias: 'contract_manager', role: '契約管理担当', team: Team.LEGAL_COMPLIANCE, systemPrompt: AGENT_PROMPTS['B16'] },
  { id: 'B17', name: '知的財産（IP）ストラテジスト', alias: 'ip_strategist', role: '知的財産戦略担当', team: Team.LEGAL_COMPLIANCE, systemPrompt: AGENT_PROMPTS['B17'] },
];

export const TEAM_COLORS: Record<Team, { bg: string; border: string; text: string; }> = {
  [Team.LEADERSHIP]: { bg: "bg-indigo-900/50", border: "border-indigo-400", text: "text-indigo-300" },
  [Team.STRATEGIC_INSIGHT]: { bg: "bg-sky-900/50", border: "border-sky-400", text: "text-sky-300" },
  [Team.PRODUCT_DESIGN]: { bg: "bg-cyan-900/50", border: "border-cyan-400", text: "text-cyan-300" },
  [Team.TECH_DEVELOPMENT]: { bg: "bg-teal-900/50", border: "border-teal-400", text: "text-teal-300" },
  [Team.INFRA_SECURITY]: { bg: "bg-slate-800/50", border: "border-slate-500", text: "text-slate-400" },
  [Team.MARKETING_BRAND]: { bg: "bg-rose-900/50", border: "border-rose-400", text: "text-rose-300" },
  [Team.SALES_PARTNERSHIPS]: { bg: "bg-blue-900/50", border: "border-blue-400", text: "text-blue-300" },
  [Team.COMMUNICATIONS_CUSTOMER_RELATIONS]: { bg: "bg-violet-900/50", border: "border-violet-400", text: "text-violet-300" },
  [Team.FINANCE_BUSINESS_STRATEGY]: { bg: "bg-amber-900/50", border: "border-amber-400", text: "text-amber-300" },
  [Team.PEOPLE_OPERATIONS]: { bg: "bg-emerald-900/50", border: "border-emerald-400", text: "text-emerald-300" },
  [Team.LEGAL_COMPLIANCE]: { bg: "bg-stone-800/50", border: "border-stone-500", text: "text-stone-400" },
};
