import { Agent, Team } from './types';
import { AGENT_PROMPTS } from './prompts/agentPrompts';

export const AGENTS: Agent[] = [
  {
    id: 'president',
    name: 'プレジデント',
    alias: 'president',
    role: '最高意思決定者',
    team: Team.LEADERSHIP,
    systemPrompt: AGENT_PROMPTS['president'],
  },
  {
    id: 'orchestrator',
    name: 'プロジェクト・オーケストレーター',
    alias: 'orchestrator',
    role: '統括管理者',
    team: Team.LEADERSHIP,
    systemPrompt: AGENT_PROMPTS['orchestrator'],
  },
  {
    id: 'A1',
    name: 'マーケット・アナリスト',
    alias: 'analyst',
    role: '市場分析官',
    team: Team.INSIGHT,
    systemPrompt: AGENT_PROMPTS['A1'],
  },
  {
    id: 'A2',
    name: 'ユーザー・エスノグラファー',
    alias: 'ethno',
    role: 'ユーザー洞察専門家',
    team: Team.INSIGHT,
    systemPrompt: AGENT_PROMPTS['A2'],
  },
  {
    id: 'A3',
    name: 'アイデア・ジェネレーター',
    alias: 'idea',
    role: 'アイデア発想家',
    team: Team.CREATIVE,
    systemPrompt: AGENT_PROMPTS['A3'],
  },
  {
    id: 'A4',
    name: 'UXアーキテクト',
    alias: 'ux',
    role: '体験設計士',
    team: Team.CREATIVE,
    systemPrompt: AGENT_PROMPTS['A4'],
  },
  {
    id: 'A5',
    name: 'テック・フィジビリティ・チェッカー',
    alias: 'tech',
    role: '技術実現性評価者',
    team: Team.REALITY_GROWTH,
    systemPrompt: AGENT_PROMPTS['A5'],
  },
  {
    id: 'A6',
    name: 'リスク・アセッサー',
    alias: 'risk',
    role: 'リスク評価官',
    team: Team.REALITY_GROWTH,
    systemPrompt: AGENT_PROMPTS['A6'],
  },
  {
    id: 'A7',
    name: 'ビジネス・ストラテジスト',
    alias: 'biz',
    role: '事業戦略家',
    team: Team.REALITY_GROWTH,
    systemPrompt: AGENT_PROMPTS['A7'],
  },
  {
    id: 'A8',
    name: 'UI/UXデザイナー',
    alias: 'design',
    role: 'UI/UX設計者',
    team: Team.CREATIVE,
    systemPrompt: AGENT_PROMPTS['A8'],
  },
  {
    id: 'A9',
    name: 'コピーライター',
    alias: 'copy',
    role: '言葉の専門家',
    team: Team.CREATIVE,
    systemPrompt: AGENT_PROMPTS['A9'],
  },
  {
    id: 'A10',
    name: 'データ・ビジュアライザー',
    alias: 'viz',
    role: 'データ可視化担当',
    team: Team.INSIGHT,
    systemPrompt: AGENT_PROMPTS['A10'],
  },
  {
    id: 'A11',
    name: 'トレンド・フォーキャスター',
    alias: 'forecast',
    role: '未来予測アナリスト',
    team: Team.INSIGHT,
    systemPrompt: AGENT_PROMPTS['A11'],
  },
  {
    id: 'A12',
    name: 'リーガル・アドバイザー',
    alias: 'legal',
    role: '法務・コンプライアンス担当',
    team: Team.REALITY_GROWTH,
    systemPrompt: AGENT_PROMPTS['A12'],
  },
  {
    id: 'A13',
    name: 'セキュリティ・アーキテクト',
    alias: 'security',
    role: '情報セキュリティ専門家',
    team: Team.REALITY_GROWTH,
    systemPrompt: AGENT_PROMPTS['A13'],
  },
  {
    id: 'A14',
    name: 'Go-to-Market スペシャリスト',
    alias: 'gtm',
    role: '市場投入戦略家',
    team: Team.REALITY_GROWTH,
    systemPrompt: AGENT_PROMPTS['A14'],
  },
  {
    id: 'A15',
    name: 'QA & エシックス・エンジニア',
    alias: 'qa',
    role: '品質・倫理監査官',
    team: Team.REALITY_GROWTH,
    systemPrompt: AGENT_PROMPTS['A15'],
  }
];

export const TEAM_COLORS: Record<Team, { bg: string; border: string; text: string; }> = {
  [Team.LEADERSHIP]: { bg: "bg-indigo-900/50", border: "border-indigo-400", text: "text-indigo-300" },
  [Team.INSIGHT]: { bg: "bg-cyan-900/50", border: "border-cyan-400", text: "text-cyan-300" },
  [Team.CREATIVE]: { bg: "bg-teal-900/50", border: "border-teal-400", text: "text-teal-300" },
  [Team.REALITY_GROWTH]: { bg: "bg-amber-900/50", border: "border-amber-400", text: "text-amber-300" },
};
